In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [6]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
newarr = arr.reshape(2,6)

In [8]:
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
for i in range(10):
    print(i , end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [13]:
print(np.cos(np.pi))

-1.0
